sudo: required

services:
  - docker

# Sign into docker then
# build, run, test,
# and push  the image
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t jabaridash/mobile-icon .
  - |
    docker run             \
    -d                     \
    -p 8080:80             \
    --name mobile-icon     \
    jabaridash/mobile-icon
  - sleep 10
  - docker ps -a
  - cd src
  - npm test
  - docker push jabaridash/mobile-icon

on:
  branch: master
