language: node_js
node_js:
  - "10.1"

sudo: required

services:
  - docker

cache:
  directories:
    - src/node_modules

before_script:
  - cd src
  - npm install

script:
  - npm test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t jabaridash/mobile-icon .
  - docker push jabaridash/mobile-icon

on:
  branch: master
