name: Build , Test, and Deploy

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Install Function Dependencies
        run: npm install
        working-directory: ./functions

      # - name: Test Functions
      #   run: npm test
      #   working-directory: ./functions
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -m $GITHUB_SHA
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
