name: Build , Test, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build , Test, and Deploy
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Install Function Dependencies
        working-directory: ./functions
        run: |
          npm install
          rm -rf node_modules/sharp
          npm install --arch=x64 --platform=linux --build-from-source sharp

      # - name: Test Functions
      #   run: npm test
      #   working-directory: ./functions

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -m $GITHUB_SHA
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
