name: Build , Test, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build , Test, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Install Function Dependencies
        run: npm install --build-from-source
        working-directory: ./functions

      # - name: Test Functions
      #   run: npm test
      #   working-directory: ./functions

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -m $GITHUB_SHA
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
